import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import Card from "../components/card";
import coffeeStoresData from "../../coffee-stores.json";

const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  };
}

export default function Home({ coffeeStores }) {
  const handleHomeBtnClick = () => {
    console.log("hi");
  };

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner btnClick={handleHomeBtnClick} btnText={"View stores nearby"} />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="person drinking coffee"
            width={700}
            height={400}
          />
        </div>
        {coffeeStores && (
          <>
            <h2 className={styles.heading2}>Toronto Coffee Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((item) => {
                return (
                  <Card
                    key={item.id}
                    imgUrl={item.imgUrl}
                    name={item.name}
                    link={"/coffee-store/" + item.id}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </>
  );
}
