import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const handleHomeBtnClick = () => {
    console.log("hi");
  };

  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner btnClick={handleHomeBtnClick} btnText={"View stores nearby"} />
      </main>
    </>
  );
}
